# Generated by Django 5.0.1 on 2024-01-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover_image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
