# Generated by Django 5.0.1 on 2024-01-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartitem', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitemmodel',
            old_name='bookId',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='cartitemmodel',
            old_name='userId',
            new_name='user',
        ),
    ]
